DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  is_paid BOOLEAN NOT NULL DEFAULT FALSE,
  client_id INTEGER REFERENCES clients(id) ON DELETE CASCADE
);
